### ISSUE TITLE
i get error when confirm email account .  domain/activateUser?type=activate&signature=c96c4ba3e43c551f1c0b3b06f40a1df8  error 404 

### ISSUE THREAD

**Issue by xzipt** [mofhy/mofhy#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jaikt** [comment]
Try to install on subdomain.
