### ISSUE TITLE
How do i install mofhy properly

### ISSUE THREAD

**Issue by AgentDeath253** [mofhy/mofhy#12]
when i try to install and it asks for the url every way i have done it messes up the installation how do i do this properly

**Comment by Gouravyadavyt** [comment]
Url please enter /after url

**Comment by Gouravyadavyt** [comment]
And send a error puc

**Comment by vellerius** [comment]
yeah new account
when im installing it now its getting a new error ill send a screenshot

**Comment by vellerius** [comment]
@Gouravyadavyt

**Comment by vellerius** [comment]
function/signup.php is broken please fix it besides that i fixed some of the code

**Comment by Gouravyadavyt** [comment]
Send please error detail

**Comment by agentdeath253** [comment]
![Screenshot (49)](https://user-images.githubusercontent.com/82530339/180895593-2c9763ee-68ec-499c-b545-6b5980c8e83d.png)

**Comment by agentdeath253** [comment]
that is a parked domain

**Comment by agentdeath253** [comment]
nvm fixed it
