### ISSUE TITLE
List of suggestions

### ISSUE THREAD

**Issue by FuryCraft** [mofhy/mofhy#5]
- Add HCaptcha & Google Recaptcha support (Bots will not create accounts)
- Add an option to choose what Captcha we want to use (or if we don't)
- Add a language file (all messages will be in this file, it's better for other people who speak an other language like me (french) to translate at every update. Maybe in a .json file)
- Detect the browser language to display Mofhy in the right language (only if a respective file is created otherwise it displays Mofhy in English)
- Integrate IFastNet or other domain resseller
- Integrate Google Analytics (option in admin settings to set the GA Id)
- Writte a Privacy Policy (cookies used by Mofhy) & a Terms Of Use text (integrate IFastNet and GoGetSSL terms of use in Mofhy. It's better for the security of the enterprise who use Mofhy)
- Update checker
- Seo options to set the description, the name of the website, the favicon & more...
- Add Site.pro integration
- Add external auth like Discord, Google, Facebook
- Add an option in the admin panel to set if Mofhy will use only classic login & signup forms or external auth or the both
- Add an option to set the `<div>` for ads in the admin panel instead of editing all pages
> I'm sorry for my English. It is so bad

**Comment by jaikt** [comment]
> Integrate IFastNet or other domain resseller

can you elaborate about wdym by this?

**Comment by jaikt** [comment]
moving this to discussions
