### ISSUE TITLE
You just made the security here even worse

### ISSUE THREAD

**Issue by greenreader9** [mofhy/mofhy#7]
https://github.com/mofhy/mofhy/commit/7b6a0e0f07666f4c5ea17cdbbad40fb9f95ef1dd

WTF is that? Every good developer knows that SESSIONS are better then COOKIES. WHY did you change it? It was working just fine, and you just made it worse.

**Comment by jaikt** [comment]
Firstly, mind your language. Thanks for letting me know. I will update it.
